// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/goamp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	MusicbrainzId string                 `protobuf:"bytes,4,opt,name=musicbrainz_id,json=musicbrainzId,proto3" json:"musicbrainz_id,omitempty"`
	DurationSecs  uint32                 `protobuf:"varint,5,opt,name=duration_secs,json=durationSecs,proto3" json:"duration_secs,omitempty"`
	Genre         string                 `protobuf:"bytes,6,opt,name=genre,proto3" json:"genre,omitempty"`
	PeerCount     uint32                 `protobuf:"varint,7,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_proto_goamp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Track) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetMusicbrainzId() string {
	if x != nil {
		return x.MusicbrainzId
	}
	return ""
}

func (x *Track) GetDurationSecs() uint32 {
	if x != nil {
		return x.DurationSecs
	}
	return 0
}

func (x *Track) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Track) GetPeerCount() uint32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Genres        []string               `protobuf:"bytes,2,rep,name=genres,proto3" json:"genres,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_goamp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_goamp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type AnnounceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceRequest) Reset() {
	*x = AnnounceRequest{}
	mi := &file_proto_goamp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceRequest) ProtoMessage() {}

func (x *AnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceRequest.ProtoReflect.Descriptor instead.
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{3}
}

func (x *AnnounceRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *AnnounceRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceUnixTs   int64                  `protobuf:"varint,1,opt,name=since_unix_ts,json=sinceUnixTs,proto3" json:"since_unix_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_goamp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{4}
}

func (x *SyncRequest) GetSinceUnixTs() int64 {
	if x != nil {
		return x.SinceUnixTs
	}
	return 0
}

type SyncBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncBatch) Reset() {
	*x = SyncBatch{}
	mi := &file_proto_goamp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBatch) ProtoMessage() {}

func (x *SyncBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBatch.ProtoReflect.Descriptor instead.
func (*SyncBatch) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{5}
}

func (x *SyncBatch) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *SyncBatch) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type TasteProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	LikedHashes   []string               `protobuf:"bytes,2,rep,name=liked_hashes,json=likedHashes,proto3" json:"liked_hashes,omitempty"`
	ListenPairs   []*ListenPair          `protobuf:"bytes,3,rep,name=listen_pairs,json=listenPairs,proto3" json:"listen_pairs,omitempty"`
	GenreWeights  map[string]float32     `protobuf:"bytes,4,rep,name=genre_weights,json=genreWeights,proto3" json:"genre_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	TotalListens   uint32                 `protobuf:"varint,5,opt,name=total_listens,json=totalListens,proto3" json:"total_listens,omitempty"`
	Proofs         []*ListeningProof      `protobuf:"bytes,6,rep,name=proofs,proto3" json:"proofs,omitempty"`
	MoodCentroids  map[string]*MoodCentroid `json:"mood_centroids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TasteProfile) Reset() {
	*x = TasteProfile{}
	mi := &file_proto_goamp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasteProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasteProfile) ProtoMessage() {}

func (x *TasteProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasteProfile.ProtoReflect.Descriptor instead.
func (*TasteProfile) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{6}
}

func (x *TasteProfile) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TasteProfile) GetLikedHashes() []string {
	if x != nil {
		return x.LikedHashes
	}
	return nil
}

func (x *TasteProfile) GetListenPairs() []*ListenPair {
	if x != nil {
		return x.ListenPairs
	}
	return nil
}

func (x *TasteProfile) GetGenreWeights() map[string]float32 {
	if x != nil {
		return x.GenreWeights
	}
	return nil
}

func (x *TasteProfile) GetTotalListens() uint32 {
	if x != nil {
		return x.TotalListens
	}
	return 0
}

func (x *TasteProfile) GetProofs() []*ListeningProof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

func (x *TasteProfile) GetMoodCentroids() map[string]*MoodCentroid {
	if x != nil {
		return x.MoodCentroids
	}
	return nil
}

type ListenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackHashA    string                 `protobuf:"bytes,1,opt,name=track_hash_a,json=trackHashA,proto3" json:"track_hash_a,omitempty"`
	TrackHashB    string                 `protobuf:"bytes,2,opt,name=track_hash_b,json=trackHashB,proto3" json:"track_hash_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenPair) Reset() {
	*x = ListenPair{}
	mi := &file_proto_goamp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenPair) ProtoMessage() {}

func (x *ListenPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenPair.ProtoReflect.Descriptor instead.
func (*ListenPair) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{7}
}

func (x *ListenPair) GetTrackHashA() string {
	if x != nil {
		return x.TrackHashA
	}
	return ""
}

func (x *ListenPair) GetTrackHashB() string {
	if x != nil {
		return x.TrackHashB
	}
	return ""
}

type ListeningProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackHash     string                 `protobuf:"bytes,1,opt,name=track_hash,json=trackHash,proto3" json:"track_hash,omitempty"`
	StartedAt     int64                  `protobuf:"varint,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	DurationSecs  int32                  `protobuf:"varint,3,opt,name=duration_secs,json=durationSecs,proto3" json:"duration_secs,omitempty"`
	ListenedSecs  int32                  `protobuf:"varint,4,opt,name=listened_secs,json=listenedSecs,proto3" json:"listened_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListeningProof) Reset() {
	*x = ListeningProof{}
	mi := &file_proto_goamp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListeningProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListeningProof) ProtoMessage() {}

func (x *ListeningProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListeningProof.ProtoReflect.Descriptor instead.
func (*ListeningProof) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{8}
}

func (x *ListeningProof) GetTrackHash() string {
	if x != nil {
		return x.TrackHash
	}
	return ""
}

func (x *ListeningProof) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ListeningProof) GetDurationSecs() int32 {
	if x != nil {
		return x.DurationSecs
	}
	return 0
}

func (x *ListeningProof) GetListenedSecs() int32 {
	if x != nil {
		return x.ListenedSecs
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_goamp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_proto_goamp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{10}
}

func (x *EventAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeVersion   string                 `protobuf:"bytes,1,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_goamp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRequest) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

type PluginManifest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SearchProviders []string               `protobuf:"bytes,3,rep,name=search_providers,json=searchProviders,proto3" json:"search_providers,omitempty"`
	Protocols       []string               `protobuf:"bytes,4,rep,name=protocols,proto3" json:"protocols,omitempty"`
	HttpRoutes      []string               `protobuf:"bytes,5,rep,name=http_routes,json=httpRoutes,proto3" json:"http_routes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_proto_goamp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{12}
}

func (x *PluginManifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetSearchProviders() []string {
	if x != nil {
		return x.SearchProviders
	}
	return nil
}

func (x *PluginManifest) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *PluginManifest) GetHttpRoutes() []string {
	if x != nil {
		return x.HttpRoutes
	}
	return nil
}

type StreamURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamURLRequest) Reset() {
	*x = StreamURLRequest{}
	mi := &file_proto_goamp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamURLRequest) ProtoMessage() {}

func (x *StreamURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamURLRequest.ProtoReflect.Descriptor instead.
func (*StreamURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{13}
}

func (x *StreamURLRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *StreamURLRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type StreamURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamURLResponse) Reset() {
	*x = StreamURLResponse{}
	mi := &file_proto_goamp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamURLResponse) ProtoMessage() {}

func (x *StreamURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goamp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamURLResponse.ProtoReflect.Descriptor instead.
func (*StreamURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_goamp_proto_rawDescGZIP(), []int{14}
}

func (x *StreamURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StreamURLResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_proto_goamp_proto protoreflect.FileDescriptor

const file_proto_goamp_proto_rawDesc = "" +
	"\n" +
	"\x11proto/goamp.proto\x12\x05goamp\"\xc6\x01\n" +
	"\x05Track\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\x0emusicbrainz_id\x18\x04 \x01(\tR\rmusicbrainzId\x12#\n" +
	"\rduration_secs\x18\x05 \x01(\rR\fdurationSecs\x12\x14\n" +
	"\x05genre\x18\x06 \x01(\tR\x05genre\x12\x1d\n" +
	"\n" +
	"peer_count\x18\a \x01(\rR\tpeerCount\"S\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06genres\x18\x02 \x03(\tR\x06genres\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"6\n" +
	"\x0eSearchResponse\x12$\n" +
	"\x06tracks\x18\x01 \x03(\v2\f.goamp.TrackR\x06tracks\"J\n" +
	"\x0fAnnounceRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"1\n" +
	"\vSyncRequest\x12\"\n" +
	"\rsince_unix_ts\x18\x01 \x01(\x03R\vsinceUnixTs\"L\n" +
	"\tSyncBatch\x12$\n" +
	"\x06tracks\x18\x01 \x03(\v2\f.goamp.TrackR\x06tracks\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xe2\x02\n" +
	"\fTasteProfile\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12!\n" +
	"\fliked_hashes\x18\x02 \x03(\tR\vlikedHashes\x124\n" +
	"\flisten_pairs\x18\x03 \x03(\v2\x11.goamp.ListenPairR\vlistenPairs\x12J\n" +
	"\rgenre_weights\x18\x04 \x03(\v2%.goamp.TasteProfile.GenreWeightsEntryR\fgenreWeights\x12#\n" +
	"\rtotal_listens\x18\x05 \x01(\rR\ftotalListens\x12-\n" +
	"\x06proofs\x18\x06 \x03(\v2\x15.goamp.ListeningProofR\x06proofs\x1a?\n" +
	"\x11GenreWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"P\n" +
	"\n" +
	"ListenPair\x12 \n" +
	"\ftrack_hash_a\x18\x01 \x01(\tR\n" +
	"trackHashA\x12 \n" +
	"\ftrack_hash_b\x18\x02 \x01(\tR\n" +
	"trackHashB\"\x98\x01\n" +
	"\x0eListeningProof\x12\x1d\n" +
	"\n" +
	"track_hash\x18\x01 \x01(\tR\ttrackHash\x12\x1d\n" +
	"\n" +
	"started_at\x18\x02 \x01(\x03R\tstartedAt\x12#\n" +
	"\rduration_secs\x18\x03 \x01(\x05R\fdurationSecs\x12#\n" +
	"\rlistened_secs\x18\x04 \x01(\x05R\flistenedSecs\"5\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x1a\n" +
	"\bEventAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"4\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fnode_version\x18\x01 \x01(\tR\vnodeVersion\"\xa4\x01\n" +
	"\x0ePluginManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10search_providers\x18\x03 \x03(\tR\x0fsearchProviders\x12\x1c\n" +
	"\tprotocols\x18\x04 \x03(\tR\tprotocols\x12\x1f\n" +
	"\vhttp_routes\x18\x05 \x03(\tR\n" +
	"httpRoutes\"N\n" +
	"\x10StreamURLRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\"D\n" +
	"\x11StreamURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt2\xed\x01\n" +
	"\vGoampPlugin\x129\n" +
	"\bRegister\x12\x16.goamp.RegisterRequest\x1a\x15.goamp.PluginManifest\x125\n" +
	"\x06Search\x12\x14.goamp.SearchRequest\x1a\x15.goamp.SearchResponse\x12>\n" +
	"\tStreamURL\x12\x17.goamp.StreamURLRequest\x1a\x18.goamp.StreamURLResponse\x12,\n" +
	"\vHandleEvent\x12\f.goamp.Event\x1a\x0f.goamp.EventAckB\x1cZ\x1agithub.com/goamp/sdk/protob\x06proto3"

var (
	file_proto_goamp_proto_rawDescOnce sync.Once
	file_proto_goamp_proto_rawDescData []byte
)

func file_proto_goamp_proto_rawDescGZIP() []byte {
	file_proto_goamp_proto_rawDescOnce.Do(func() {
		file_proto_goamp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goamp_proto_rawDesc), len(file_proto_goamp_proto_rawDesc)))
	})
	return file_proto_goamp_proto_rawDescData
}

var file_proto_goamp_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_goamp_proto_goTypes = []any{
	(*Track)(nil),             // 0: goamp.Track
	(*SearchRequest)(nil),     // 1: goamp.SearchRequest
	(*SearchResponse)(nil),    // 2: goamp.SearchResponse
	(*AnnounceRequest)(nil),   // 3: goamp.AnnounceRequest
	(*SyncRequest)(nil),       // 4: goamp.SyncRequest
	(*SyncBatch)(nil),         // 5: goamp.SyncBatch
	(*TasteProfile)(nil),      // 6: goamp.TasteProfile
	(*ListenPair)(nil),        // 7: goamp.ListenPair
	(*ListeningProof)(nil),    // 8: goamp.ListeningProof
	(*Event)(nil),             // 9: goamp.Event
	(*EventAck)(nil),          // 10: goamp.EventAck
	(*RegisterRequest)(nil),   // 11: goamp.RegisterRequest
	(*PluginManifest)(nil),    // 12: goamp.PluginManifest
	(*StreamURLRequest)(nil),  // 13: goamp.StreamURLRequest
	(*StreamURLResponse)(nil), // 14: goamp.StreamURLResponse
	nil,                       // 15: goamp.TasteProfile.GenreWeightsEntry
}
var file_proto_goamp_proto_depIdxs = []int32{
	0,  // 0: goamp.SearchResponse.tracks:type_name -> goamp.Track
	0,  // 1: goamp.SyncBatch.tracks:type_name -> goamp.Track
	7,  // 2: goamp.TasteProfile.listen_pairs:type_name -> goamp.ListenPair
	15, // 3: goamp.TasteProfile.genre_weights:type_name -> goamp.TasteProfile.GenreWeightsEntry
	8,  // 4: goamp.TasteProfile.proofs:type_name -> goamp.ListeningProof
	11, // 5: goamp.GoampPlugin.Register:input_type -> goamp.RegisterRequest
	1,  // 6: goamp.GoampPlugin.Search:input_type -> goamp.SearchRequest
	13, // 7: goamp.GoampPlugin.StreamURL:input_type -> goamp.StreamURLRequest
	9,  // 8: goamp.GoampPlugin.HandleEvent:input_type -> goamp.Event
	12, // 9: goamp.GoampPlugin.Register:output_type -> goamp.PluginManifest
	2,  // 10: goamp.GoampPlugin.Search:output_type -> goamp.SearchResponse
	14, // 11: goamp.GoampPlugin.StreamURL:output_type -> goamp.StreamURLResponse
	10, // 12: goamp.GoampPlugin.HandleEvent:output_type -> goamp.EventAck
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_goamp_proto_init() }
func file_proto_goamp_proto_init() {
	if File_proto_goamp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goamp_proto_rawDesc), len(file_proto_goamp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goamp_proto_goTypes,
		DependencyIndexes: file_proto_goamp_proto_depIdxs,
		MessageInfos:      file_proto_goamp_proto_msgTypes,
	}.Build()
	File_proto_goamp_proto = out.File
	file_proto_goamp_proto_goTypes = nil
	file_proto_goamp_proto_depIdxs = nil
}
