// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/goamp.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoampPlugin_Register_FullMethodName    = "/goamp.GoampPlugin/Register"
	GoampPlugin_Search_FullMethodName      = "/goamp.GoampPlugin/Search"
	GoampPlugin_StreamURL_FullMethodName   = "/goamp.GoampPlugin/StreamURL"
	GoampPlugin_HandleEvent_FullMethodName = "/goamp.GoampPlugin/HandleEvent"
)

// GoampPluginClient is the client API for GoampPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoampPluginClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*PluginManifest, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	StreamURL(ctx context.Context, in *StreamURLRequest, opts ...grpc.CallOption) (*StreamURLResponse, error)
	HandleEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventAck, error)
}

type goampPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewGoampPluginClient(cc grpc.ClientConnInterface) GoampPluginClient {
	return &goampPluginClient{cc}
}

func (c *goampPluginClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*PluginManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginManifest)
	err := c.cc.Invoke(ctx, GoampPlugin_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goampPluginClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, GoampPlugin_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goampPluginClient) StreamURL(ctx context.Context, in *StreamURLRequest, opts ...grpc.CallOption) (*StreamURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamURLResponse)
	err := c.cc.Invoke(ctx, GoampPlugin_StreamURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goampPluginClient) HandleEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventAck)
	err := c.cc.Invoke(ctx, GoampPlugin_HandleEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoampPluginServer is the server API for GoampPlugin service.
// All implementations must embed UnimplementedGoampPluginServer
// for forward compatibility.
type GoampPluginServer interface {
	Register(context.Context, *RegisterRequest) (*PluginManifest, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	StreamURL(context.Context, *StreamURLRequest) (*StreamURLResponse, error)
	HandleEvent(context.Context, *Event) (*EventAck, error)
	mustEmbedUnimplementedGoampPluginServer()
}

// UnimplementedGoampPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoampPluginServer struct{}

func (UnimplementedGoampPluginServer) Register(context.Context, *RegisterRequest) (*PluginManifest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGoampPluginServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGoampPluginServer) StreamURL(context.Context, *StreamURLRequest) (*StreamURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamURL not implemented")
}
func (UnimplementedGoampPluginServer) HandleEvent(context.Context, *Event) (*EventAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleEvent not implemented")
}
func (UnimplementedGoampPluginServer) mustEmbedUnimplementedGoampPluginServer() {}
func (UnimplementedGoampPluginServer) testEmbeddedByValue()                     {}

// UnsafeGoampPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoampPluginServer will
// result in compilation errors.
type UnsafeGoampPluginServer interface {
	mustEmbedUnimplementedGoampPluginServer()
}

func RegisterGoampPluginServer(s grpc.ServiceRegistrar, srv GoampPluginServer) {
	// If the following call pancis, it indicates UnimplementedGoampPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoampPlugin_ServiceDesc, srv)
}

func _GoampPlugin_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoampPluginServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoampPlugin_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoampPluginServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoampPlugin_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoampPluginServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoampPlugin_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoampPluginServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoampPlugin_StreamURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoampPluginServer).StreamURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoampPlugin_StreamURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoampPluginServer).StreamURL(ctx, req.(*StreamURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoampPlugin_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoampPluginServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoampPlugin_HandleEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoampPluginServer).HandleEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// GoampPlugin_ServiceDesc is the grpc.ServiceDesc for GoampPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoampPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goamp.GoampPlugin",
	HandlerType: (*GoampPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GoampPlugin_Register_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _GoampPlugin_Search_Handler,
		},
		{
			MethodName: "StreamURL",
			Handler:    _GoampPlugin_StreamURL_Handler,
		},
		{
			MethodName: "HandleEvent",
			Handler:    _GoampPlugin_HandleEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/goamp.proto",
}
